name: Build on Push to release

on:
  push:
    branches: 
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      APP_NAME: dart_native_executables

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Build
        run: |
          pub get
          dart tool/grind.dart clean build

      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: build/*
          tags: true
          draft: false