name: Build on Push to release

on:
  push:
    branches: 
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      APP_NAME: dart_native_executables

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: ${GITHUB_REPOSITORY##*/}-linux
          - os: macOS-latest
            output-name: ${GITHUB_REPOSITORY##*/}-mac
          - os: windows-latest
            output-name: ${GITHUB_REPOSITORY##*/}-windows.exe

    steps:
      - uses: actions/checkout@v1

      - name: Setup Dart VM
        uses: vanesyan/setup-dart@v1

      - name: Build for windows
        if: matrix.os == 'windows-latest'
        run: |
          pub.bat get
          dart.exe compile exe bin/main.dart -o build/${{ matrix.output-name }}
        shell: bash

      - name: Build for non-windows
        if: matrix.os != 'windows-latest'
        run: |
          pub get
          dart compile exe bin/main.dart -o build/${{ matrix.output-name }}
        shell: bash

      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: build/*
          tags: true
          draft: false